model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "MSE/Validation_epoch" # name of the logged metric which determines when model is improving
  mode: "min" # can be "max" or "min"
  save_top_k: 1 # save k best models (determined by above metric)
  save_last: True # additionaly always save model from last epoch
  verbose: False
  dirpath: "checkpoints/"
  filename: "epoch_{epoch:03d}"
  auto_insert_metric_name: False

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "MSE/Validation_epoch" # name of the logged metric which determines when model is improving
  mode: "min" # can be "max" or "min"
  patience: 5 # how many epochs of not improving until training stops
  min_delta: 0 # minimum change in the monitored metric needed to qualify as an improvement

hugging_face:
  _target_: hf_hub_lightning.callback.HuggingFaceHubCallback
  repo_name: Openclimatefix/nowcasting_cnn
